#ifndef FONTSIZE_HPP
#define FONTSIZE_HPP

#define FONTSIZE_TITLE
#define FONTSIZE_SUBTITLE
#define FONTSIZE_XXLARGE
#define FONTSIZE_XLARGE
#define FONTSIZE_LARGE
#define FONTSIZE_MEDIUM
#define FONTSIZE_SMALL
#define FONTSIZE_XSMALL
#define FONTSIZE_XXSMALL

#endif
